apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: NodePort
  selector:
    project: kubernetes-project
    tier: frontend
    app: application
  ports:
    - name: "application"
      nodePort: 31111
      port: 3000
      targetPort: 3000
