apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  selector:
    matchLabels:
      app: database
      project: kubernetes-project
      tier: backend
  template:
    metadata:
      labels:
        project: kubernetes-project
        tier: backend
        app: database
    spec:
        containers:
        - name: postgres-image
          image: postgres:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5432
          envFrom:
          - configMapRef:
                name: database-configmap

          
        
        
